apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.44.0
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
          resources:               # Add resource requests and limits
            requests:
              cpu: "100m"         # Adjust as needed
              memory: "128Mi"     # Adjust as needed
            limits:
              cpu: "200m"         # Adjust as needed
              memory: "256Mi"     # Adjust as needed
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config

